# Gradle settings
org.gradle.parallel = true
org.gradle.jvmargs = -Xmx4096M
org.gradle.daemon = false
# Plugin versions
NeoGradle = 7.0.+
CurseForge = 0.6.1
# Minecraft
MinecraftVersion = 1.21.10
MinecraftVersionRange = [1.21.10,1.22)
# NeoForge
NeoForgeVersion = 21.10.64
NeoForgeVersionRange = [21.10,)
NeoFormVersion = 1.21.10-20251010.172816
# XBackpack
# Version in the format [major_minecaft].[minor_minecaft].[feature/bugfix]
ModVersion = 5.3.3
# Just Enough Items
JeiVersion = 26.0.0.4
