modLoader = "javafml"
loaderVersion = "${ForgeLoaderRange}"
license = "All rights reserved"

[[mods]]
modId = "xbackpack"
version = "${MinecraftVersion}-${ModVersion}"
displayName = "XBackpack"
credits = "Thanks for downloading my Mod"
authors = "Luis"
displayURL = "https://github.com/Luis-St/Forge-XBackpack/issues"
description = '''
Adds a cool Backpack to the Game
Have a lot of fun when playing
XBackpack Development Team
'''

[[dependencies.xbackpack]]
modId = "forge"
mandatory = true
versionRange = "${ForgeVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.xbackpack]]
modId = "minecraft"
mandatory = true
versionRange = "${MinecraftVersionRange}"
ordering = "NONE"
side = "BOTH"
